# Generated by Django 5.2.8 on 2025-11-24 01:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('schema_version', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('raw_file', models.FileField(upload_to='uploaded_datasets/')),
                ('validation_report', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner'], name='ingestion_u_owner_i_ef13a7_idx'), models.Index(fields=['status'], name='ingestion_u_status_490a0c_idx'), models.Index(fields=['created_at'], name='ingestion_u_created_846f34_idx')],
            },
        ),
    ]
