"""crashsev.decision_rule_sensitivity — regenerate the decision-rule sensitivity table (DEC-001).

Deterministic, retrospective post-hoc analysis of frozen per-model predictions. No model is
retrained: the hard class is re-derived from each model's already-recorded probability vector under
three decision rules and ordinal MAE / accuracy are recomputed.

For an ordered target y in {0,1,2} with predicted probabilities p:
  * argmax           -- k' = argmax_k p_k  (minimises 0-1 loss; what the pipeline emits by default)
  * posterior median -- smallest k with cumsum_{j<=k} p_j >= 0.5  (minimises absolute/ordinal loss;
                        the rule *consistent with the primary metric, ordinal MAE*)
  * expected round   -- round(sum_k k*p_k) clipped to [0, K-1]

Runs on either the real run-bundle predictions or the shipped de-identified predictions; the
group_id column is an identifier only and never enters a metric. Output is aggregate (no per-crash
identifiers are written).

Usage:
    python -m crashsev.decision_rule_sensitivity --preds <dir-with-predictions_*.csv> --out <md>
"""
from __future__ import annotations

import argparse
import csv
import glob
import os
from typing import Dict, List, Tuple

# Pretty display names; unknown stems fall back to a de-underscored form.
DISPLAY = {
    "ordinal_random_forest": "ordinal random forest",
    "ordinal_random_forest_unweighted": "ordinal random forest (unweighted)",
    "random_forest": "random forest",
    "random_forest_unweighted": "random forest (unweighted)",
    "majority": "majority",
    "ordinal_median": "ordinal median",
    "empirical_prior": "empirical prior",
    "prior_probability": "prior probability",
    "multinomial_logistic": "multinomial logit",
    "proportional_odds": "proportional-odds logit",
    "frank_hall_logistic": "frank-hall logit",
    "shallow_tree": "shallow tree",
    "decision_tree": "decision tree",
    "xgboost": "xgboost",
    "ebm": "ebm (exploratory; final-only)",
}


def _read_preds(path: str) -> Tuple[List[int], List[List[float]], List[int]]:
    y_true: List[int] = []
    proba: List[List[float]] = []
    y_pred: List[int] = []
    with open(path, newline="", encoding="utf-8") as fh:
        r = csv.DictReader(fh)
        proba_cols = sorted([c for c in r.fieldnames or [] if c.startswith("proba_")],
                            key=lambda c: int(c.split("_")[1]))
        for row in r:
            y_true.append(int(row["y_true"]))
            y_pred.append(int(row["y_pred"]))
            proba.append([float(row[c]) for c in proba_cols] if proba_cols else [])
    return y_true, proba, y_pred


def _argmax(p: List[float]) -> int:
    return max(range(len(p)), key=lambda k: p[k])


def _posterior_median(p: List[float]) -> int:
    c = 0.0
    for k, pk in enumerate(p):
        c += pk
        if c >= 0.5:
            return k
    return len(p) - 1


def _expected_round(p: List[float]) -> int:
    ev = sum(k * pk for k, pk in enumerate(p))
    r = int(round(ev))
    return max(0, min(len(p) - 1, r))


def _omae(y_true: List[int], y_hat: List[int]) -> float:
    return sum(abs(a - b) for a, b in zip(y_hat, y_true)) / len(y_true)


def _acc(y_true: List[int], y_hat: List[int]) -> float:
    return sum(1 for a, b in zip(y_hat, y_true) if a == b) / len(y_true)


def analyse(preds_dir: str) -> List[Dict[str, object]]:
    rows: List[Dict[str, object]] = []
    for path in sorted(glob.glob(os.path.join(preds_dir, "predictions_*.csv"))):
        stem = os.path.basename(path)[len("predictions_"):-len(".csv")]
        y_true, proba, y_pred = _read_preds(path)
        n = len(y_true)
        if proba and all(len(p) for p in proba):
            arg = [_argmax(p) for p in proba]
            med = [_posterior_median(p) for p in proba]
            exr = [_expected_round(p) for p in proba]
        else:  # no probabilities: fall back to the recorded hard prediction for every rule
            arg = med = exr = y_pred
        rows.append({
            "model": stem, "n": n,
            "omae_argmax": _omae(y_true, arg), "omae_median": _omae(y_true, med),
            "omae_exp": _omae(y_true, exr),
            "acc_argmax": _acc(y_true, arg), "acc_median": _acc(y_true, med),
        })
    rows.sort(key=lambda d: d["omae_argmax"])
    return rows


def render_md(rows: List[Dict[str, object]]) -> str:
    n = rows[0]["n"] if rows else 0
    out = []
    out.append("# Decision-rule sensitivity (DECISION-LOSS-001)\n")
    out.append("**Status:** retrospective, deterministic post-hoc analysis of the frozen 2012 "
               "predictions. No model is retrained; the hard class is re-derived from each model's "
               "already-recorded probability vector under three decision rules and ordinal MAE / "
               "accuracy recomputed. Regenerated by `python -m crashsev.decision_rule_sensitivity` "
               "(output is aggregate; no per-crash identifiers).\n")
    out.append("For an ordered target y in {0,1,2} with predicted probabilities p:\n"
               "- **argmax** -- minimises 0-1 loss; what the pipeline emits by default.\n"
               "- **posterior median** -- smallest k with cumulative prob >= 0.5; the rule "
               "*consistent with the primary metric, ordinal MAE*.\n"
               "- **expected-value round** -- round(sum_k k*p_k) clipped to [0,2].\n")
    out.append(f"**Table -- ordinal MAE (lower better) and exact accuracy by decision rule, "
               f"held-out out-of-time 2012 (n = {n:,}).**\n")
    out.append("| Model | oMAE argmax | oMAE median | oMAE exp-round | acc argmax | acc median |")
    out.append("|---|---|---|---|---|---|")
    for d in rows:
        name = DISPLAY.get(str(d["model"]), str(d["model"]).replace("_", " "))
        out.append(f"| {name} | {d['omae_argmax']:.4f} | {d['omae_median']:.4f} | "
                   f"{d['omae_exp']:.4f} | {d['acc_argmax']:.4f} | {d['acc_median']:.4f} |")
    out.append("")
    return "\n".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(prog="python -m crashsev.decision_rule_sensitivity")
    ap.add_argument("--preds", required=True, help="directory containing predictions_*.csv")
    ap.add_argument("--out", required=True, help="output markdown path")
    args = ap.parse_args(argv)
    rows = analyse(args.preds)
    md = render_md(rows)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(md)
    print(f"[decision-rule] {len(rows)} models -> {args.out}")


if __name__ == "__main__":
    main()
