"""crashsev.error_analysis — bounded, privacy-safe error analysis (ERR-001).

The paper previously claimed a "full error analysis" but shipped only aggregate metrics. This module
produces an actual, reproducible error breakdown from frozen per-model predictions: the confusion
matrix, ordinal class-transition counts (with the severe-class false negatives called out),
high-confidence errors, and error rate by predicted-confidence bin. Output is aggregate only — no
per-crash identifiers, coordinates, or small identifying cells are written.

Runs on either the real run-bundle predictions or the shipped de-identified predictions.

Usage:
    python -m crashsev.error_analysis --preds <dir> --models ordinal_random_forest majority --out <md>
"""
from __future__ import annotations

import argparse
import csv
import glob
import os
from typing import Dict, List, Optional, Tuple

N_CLASSES = 3
LABELS = {0: "none/PDO", 1: "minor", 2: "serious/fatal"}


def _read(path: str):
    y_true, y_pred, proba = [], [], []
    with open(path, newline="", encoding="utf-8") as fh:
        r = csv.DictReader(fh)
        pcols = sorted([c for c in r.fieldnames or [] if c.startswith("proba_")],
                       key=lambda c: int(c.split("_")[1]))
        for row in r:
            y_true.append(int(row["y_true"]))
            y_pred.append(int(row["y_pred"]))
            proba.append([float(row[c]) for c in pcols] if pcols else None)
    return y_true, y_pred, proba


def _confusion(y_true, y_pred, k=N_CLASSES):
    cm = [[0] * k for _ in range(k)]
    for t, p in zip(y_true, y_pred):
        cm[t][p] += 1
    return cm


def analyse_model(path: str) -> Dict[str, object]:
    y_true, y_pred, proba = _read(path)
    n = len(y_true)
    cm = _confusion(y_true, y_pred)
    # ordinal transition counts (true -> pred where they differ)
    transitions = {f"{t}->{p}": cm[t][p] for t in range(N_CLASSES) for p in range(N_CLASSES) if t != p}
    severe_support = sum(cm[2])
    severe_fn = cm[2][0] + cm[2][1]            # true serious/fatal predicted lower
    severe_fn_2to0 = cm[2][0]                  # the worst ordinal error (off by 2)
    false_severe = cm[0][2] + cm[1][2]         # predicted serious/fatal but truly lower
    # high-confidence errors (max prob >= 0.8 yet wrong) and confidence-binned error
    hi_conf_err = None
    conf_bins = None
    if proba and all(p is not None for p in proba):
        thr = 0.8
        hi = [(pr, t, pr.index(max(pr))) for pr, t in zip(proba, y_true)]
        hi_conf_total = sum(1 for pr, t, ph in hi if max(pr) >= thr)
        hi_conf_wrong = sum(1 for pr, t, ph in hi if max(pr) >= thr and ph != t)
        hi_conf_err = {"threshold": thr, "n_high_conf": hi_conf_total,
                       "n_high_conf_wrong": hi_conf_wrong,
                       "high_conf_error_rate": (hi_conf_wrong / hi_conf_total) if hi_conf_total else None}
        edges = [(0.0, 0.4), (0.4, 0.6), (0.6, 0.8), (0.8, 1.01)]
        conf_bins = []
        for lo, hiedge in edges:
            idx = [i for i, pr in enumerate(proba) if lo <= max(pr) < hiedge]
            if idx:
                wrong = sum(1 for i in idx if proba[i].index(max(proba[i])) != y_true[i])
                conf_bins.append({"bin": f"[{lo:.1f},{hiedge:.1f})", "n": len(idx),
                                  "error_rate": wrong / len(idx)})
    return {"n": n, "confusion": cm, "transitions": transitions,
            "severe_support": severe_support, "severe_false_negatives": severe_fn,
            "severe_2to0_worst_errors": severe_fn_2to0, "false_severe_alarms": false_severe,
            "high_confidence_errors": hi_conf_err, "error_by_confidence_bin": conf_bins}


def render_md(results: Dict[str, dict]) -> str:
    out = ["# Error analysis (ERR-001)\n",
           "Bounded, reproducible, privacy-safe error breakdown of the frozen 2012 predictions "
           "(aggregate only; no per-crash identifiers). Regenerated by "
           "`python -m crashsev.error_analysis`.\n"]
    for name, r in results.items():
        out.append(f"## {name}  (n = {r['n']:,})\n")
        out.append("**Confusion matrix** (rows = true, cols = predicted; classes "
                   "0 none/PDO, 1 minor, 2 serious/fatal):\n")
        out.append("| true \\ pred | 0 | 1 | 2 |")
        out.append("|---|---|---|---|")
        for t in range(N_CLASSES):
            out.append(f"| **{t}** | {r['confusion'][t][0]} | {r['confusion'][t][1]} | {r['confusion'][t][2]} |")
        out.append("")
        out.append(f"- serious/fatal (class 2) support: **{r['severe_support']}**")
        out.append(f"- serious/fatal missed (2→1 or 2→0, false negatives): **{r['severe_false_negatives']}** "
                   f"of which off-by-two (2→0, the worst ordinal error): **{r['severe_2to0_worst_errors']}**")
        out.append(f"- false serious/fatal alarms (0→2 or 1→2): **{r['false_severe_alarms']}**")
        hc = r.get("high_confidence_errors")
        if hc and hc["high_conf_error_rate"] is not None:
            out.append(f"- high-confidence errors (max prob ≥ {hc['threshold']}): "
                       f"{hc['n_high_conf_wrong']}/{hc['n_high_conf']} = "
                       f"{hc['high_conf_error_rate']:.3f} error rate")
        if r.get("error_by_confidence_bin"):
            out.append("\n**Error rate by predicted-confidence bin:**\n")
            out.append("| confidence bin | n | error rate |")
            out.append("|---|---|---|")
            for b in r["error_by_confidence_bin"]:
                out.append(f"| {b['bin']} | {b['n']} | {b['error_rate']:.3f} |")
        out.append("")
    return "\n".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(prog="python -m crashsev.error_analysis")
    ap.add_argument("--preds", required=True, help="directory with predictions_*.csv")
    ap.add_argument("--models", nargs="*", default=None, help="model stems (default: all found)")
    ap.add_argument("--out", required=True)
    args = ap.parse_args(argv)
    results: Dict[str, dict] = {}
    for path in sorted(glob.glob(os.path.join(args.preds, "predictions_*.csv"))):
        stem = os.path.basename(path)[len("predictions_"):-len(".csv")]
        if args.models and stem not in args.models:
            continue
        results[stem] = analyse_model(path)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(render_md(results))
    print(f"[error-analysis] {len(results)} model(s) -> {args.out}")


if __name__ == "__main__":
    main()
