# Generated by Django 5.2.8 on 2025-11-24 01:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('result_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_jobs', to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_jobs', to='ingestion.uploadeddataset')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner'], name='analysis_mo_owner_i_5a7f1b_idx'), models.Index(fields=['upload'], name='analysis_mo_upload__8ef967_idx'), models.Index(fields=['status'], name='analysis_mo_status_946e44_idx')],
            },
        ),
    ]
