"""Prohibited-claim and numeric-consistency scan over the paper SOURCES *and* RENDERED outputs.

PAPER-OVER-001 / PDF-001 lesson: the v3 scan checked only ``final_paper.md`` and missed stale
"sealed … grouped-bootstrap" figure captions that ``render_paper.py`` injected into the shipped
HTML/PDF, plus three §7 claims contradicted by the committed artifacts. This scan therefore:

  1. flags forbidden/status-inflating terms in the .md, the rendered .html, the READMEs, and the
     claim matrix — a line is EXEMPT only if it carries an explicit negation/correction marker
     (e.g. "not", "never", "earlier revision", "was wrong", "corrected", "stale", "scan"), and
  2. spot-checks load-bearing numbers and corrected statements against
     ``experiment/final_results.json`` and ``experiment/development_report.json``.

Exit 0 = clean; exit 1 = violations (printed). Run from ``remediation/``:
    python research_audit/claim_scan.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

PKG = Path(__file__).resolve().parents[1]

SCAN_FILES = [
    PKG / "paper" / "final_paper.md",
    PKG / "paper" / "final_paper.html",
    PKG / "paper" / "CLAIM_EVIDENCE_MATRIX.md",
    PKG / "README.md",
    PKG.parent / "README.md",
]

# Forbidden/status-inflating terms. A hit is exempt if the line carries a negation or an explicit
# correction/history marker (this is a tripwire for unqualified use, not a semantic prover).
FORBIDDEN = [
    "sealed",
    "preregistered",
    "provably",
    "grouped-bootstrap",
    "grouped bootstrap",
    "dependence-aware",
    "confirmatory",
    "cleanly separated",
    "one at a time",
    "deployment ready",
    "deployment-ready",
    "independently reproduced",
    "generated by this tagged commit",
    "never loaded",            # GOV-002: the shared table IS loaded+hashed whole; say "never interpreted"
    "unpredictable",           # P0-INTERP-001: hard-rule recall != absence of ranking signal
]

EXEMPT_MARKERS = [
    "not ", "never ", "no ", "non-", "isn't", "**not**", "rather than",
    "instead", "earlier revision", "was wrong", "wrongly", "corrected", "correction",
    "relabel", "stale", "removed", "retired", "superseded", "historical", "forbidden",
    "prohibit", "scan", "must match", "do not", "does not", "cannot", "impossible",
    "not_one_at_a_time", "not presented", "not a ", "nor ", "without ", "mislabel",
    "amendment", "misstate", "wrong",
]

_TAG = re.compile(r"<[^>]+>")


def scan_terms() -> list[str]:
    """Flag forbidden terms. Context window = previous + current line (claims wrap across
    lines); HTML is scanned with tags stripped so '<strong>not</strong>' still counts as a
    negation. A tripwire for unqualified use, not a semantic prover."""
    problems = []
    for path in SCAN_FILES:
        if not path.exists():
            problems.append(f"MISSING scan target: {path}")
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        lines = text.splitlines()
        if path.suffix.lower() in (".html", ".htm"):
            lines = [_TAG.sub(" ", ln) for ln in lines]
        for i, line in enumerate(lines, 1):
            low = line.lower()
            # context window: three previous lines + current (a negated sentence can wrap
            # across up to four hard-wrapped lines in the paper source)
            window = " ".join(lines[max(0, i - 4):i]).lower()
            for term in FORBIDDEN:
                if term in low and not any(m in window for m in EXEMPT_MARKERS):
                    problems.append(f"{path.name}:{i}: unqualified '{term}': {line.strip()[:140]}")
    return problems


def check_numbers() -> list[str]:
    problems = []
    md = (PKG / "paper" / "final_paper.md").read_text(encoding="utf-8")
    fr = json.loads((PKG / "experiment" / "final_results.json").read_text(encoding="utf-8"))
    dev = json.loads((PKG / "experiment" / "development_report.json").read_text(encoding="utf-8"))
    res = fr["results"]

    # 1. headline numbers present: v4 primary (0.3469 / 0.3614), v4 controls (0.3401 / 0.3423),
    #    the historical v3 headline retained in §7.7 (0.3310), the broad-tier sensitivity
    #    (0.3327), and the raw-file byte-identity withholding statement (r4: the hash value
    #    itself is withheld from public artifacts — restricted reproduction log).
    for s in ("0.3469", "0.3614", "0.3401", "0.3423", "0.3310", "0.3327", "restricted reproduction log"):
        if s not in md:
            problems.append(f"paper missing load-bearing value {s}")

    # 2. the actual best-oMAE model must be acknowledged in Table 2 (all-model table)
    best = min((m for m in res if "ordinal_mae" in res[m]), key=lambda m: res[m]["ordinal_mae"])
    if best == "random_forest_unweighted" and "Random forest (unweighted)" not in md:
        problems.append("Table 2 no longer lists the best-oMAE model 'Random forest (unweighted)'")

    # 3. proper-score correction must survive: unqualified superlative is forbidden
    if "best proper scores" in md and "Across **all fourteen**" not in md:
        problems.append("proper-score superlative present without the all-fourteen qualification")

    # 4. provenance: the impossible claim must stay dead; BOTH generator commits must be cited
    #    (v4: 458f784; historical v3: e55d6f1)
    for c in ("458f784", "e55d6f1"):
        if c not in md:
            problems.append(f"paper no longer cites generator commit {c}")

    # 5. development leaders (rounded) must appear in §7.2
    agg = dev["dev_cv"]["aggregate"]
    lead = sorted(agg, key=lambda m: agg[m]["mean_ordinal_mae"])[:2]
    if set(lead) == {"ordinal_random_forest_unweighted", "random_forest_unweighted"}:
        if "0.3233" not in md or "0.3246" not in md:
            problems.append("paper §7.2 missing the unweighted development leaders (0.3233/0.3246)")

    # 6. majority severe precision must be undefined in artifact and NOT printed as 0.000
    sp = res["majority"]["severe_precision"]
    if not (isinstance(sp, float) and sp != sp):
        problems.append("artifact majority severe_precision unexpectedly defined")
    if re.search(r"Majority / Ord\. median \|[^\n]*\| 0\.000 \| 1\.000 \|", md):
        problems.append("Table 2 prints 0.000 for majority severe precision (must be '—')")

    # 7. P0-RESULT-002 (fourth round): the beats-the-prior-on-all-proper-scores set is COMPUTED
    #    from the artifact, never asserted universally. The v4 sentence "every learned model
    #    beats the ... prior ... on every proper score" was FALSE (only the four forest variants
    #    qualify). Forbid the universal form; require the paper to name the computed set.
    pr = res.get("prior_probability")
    if pr and "log_loss" in pr:
        beats = sorted(m for m, v in res.items()
                       if m != "prior_probability" and isinstance(v.get("log_loss"), float)
                       and v["log_loss"] < pr["log_loss"] and v["brier"] < pr["brier"]
                       and v["rps"] < pr["rps"])
        for mt in re.finditer(r"every learned model[^.]{0,120}(?:proper score|prior)", md, re.I):
            ctx = md[mt.start(): mt.end() + 200].lower()
            if not any(k in ctx for k in ("false", "wrong", "machine-checked", "machine-computed")):
                problems.append("universal 'every learned model … prior/proper score' claim "
                                f"present (artifact set is exactly: {beats})")
                break
        if beats == ["ordinal_random_forest", "ordinal_random_forest_unweighted",
                     "random_forest", "random_forest_unweighted"]:
            if "four random-forest variants" not in md and "four forest variants" not in md:
                problems.append("paper does not name the computed beats-prior set "
                                "('four random-forest variants')")
    return problems


def main() -> int:
    problems = scan_terms() + check_numbers()
    if problems:
        print(f"CLAIM SCAN: {len(problems)} violation(s)")
        for p in problems:
            print("  *", p)
        return 1
    print("CLAIM SCAN: clean (terms + numeric spot-checks)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
