# Generated by Django 5.2.8 on 2025-11-24 01:51

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash_id', models.CharField(max_length=64)),
                ('crash_datetime', models.DateTimeField()),
                ('severity', models.CharField(choices=[('K', 'Fatal (K)'), ('A', 'Suspected serious injury (A)'), ('B', 'Suspected minor injury (B)'), ('C', 'Possible injury (C)'), ('O', 'Property damage only (O)')], max_length=1)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Crash location in WGS84 (lon/lat).', null=True, srid=4326)),
                ('roadway_name', models.CharField(blank=True, max_length=128)),
                ('municipality', models.CharField(blank=True, max_length=128)),
                ('posted_speed_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_count', models.PositiveIntegerField(blank=True, null=True)),
                ('person_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crash_records', to='ingestion.uploadeddataset')),
            ],
            options={
                'indexes': [models.Index(fields=['crash_datetime'], name='crashdata_c_crash_d_010975_idx'), models.Index(fields=['severity'], name='crashdata_c_severit_ebfddc_idx'), models.Index(fields=['dataset'], name='crashdata_c_dataset_072604_idx'), django.contrib.postgres.indexes.GistIndex(fields=['location'], name='crashdata_c_locatio_5a0110_gist')],
            },
        ),
    ]
